### ISSUE TITLE
The LuckPerms could not be found to activate the group system

### ISSUE THREAD

**Issue by horizon86** [jonagamerpro1234/CustomJoinAndQuitMessages#20]
![image](https://user-images.githubusercontent.com/49552732/210167496-de9701da-65b5-4502-a7ee-9f83fd9146e2.png)

Config.Type is normal

**Comment by jonagamerpro1234** [comment]
Hello, the problem you are having is normal in version `v1.7.5-b3`, but the problem is fixed in the latest available beta, which is [`v1.7.6-beta.3`](https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages/releases/tag/v1.7.6-Beta.3). 

In case the problem is in this version, I will need you to provide me with more information, such as the `version of the server` and the `type of jar (spigot, papermc, etc.)` to find a solution to the problem.

**Comment by horizon86** [comment]
> Hello, the problem you are having is normal in version `v1.7.5-b3`, but the problem is fixed in the latest available beta, which is [`v1.7.6-beta.3`](https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages/releases/tag/v1.7.6-Beta.3).
> 
> In case the problem is in this version, I will need you to provide me with more information, such as the `version of the server` and the `type of jar (spigot, papermc, etc.)` to find a solution to the problem.

OK，I update to v1.7.6-beta3 and solved.
